### ISSUE TITLE
2020a

### ISSUE THREAD

**Issue by guyisra** [evansiroky/node-geo-tz#106]
I know it came out a few days ago, but this can serve as a reminder to do
(unless we can do it on our own, not sure how to send a PR)

**Comment by evansiroky** [comment]
node-geo-tz uses data from [timezone-boundary-builder](https://github.com/evansiroky/timezone-boundary-builder), so is dependent on that project producing a 2020a release before a new release can happen here.

**Comment by evansiroky** [comment]
Version 6 has just been published which contains 2020a.
