### ISSUE TITLE
Set cache expiration

### ISSUE THREAD

**Issue by Mattesackboy** [evansiroky/node-geo-tz#113]
I'll need to upgrade from 5.1.0 to 6.0.1 because of the new timezone database data (2020d).
But I'd like to know why you removed the 'expires' param from the '.setCache({})' method.
Wasn't it very useful?

**Comment by evansiroky** [comment]
See #104. I think it could be useful for certain use cases, but it seemed like a too advanced default behavior. It is still possible to use the timed-cache library in an implementing application if a custom `store` variable is sent to the [`setCache`](https://github.com/evansiroky/node-geo-tz#geotzsetcacheoptions) method.
