### ISSUE TITLE
Too much large unpack size

### ISSUE THREAD

**Issue by arslanalidev** [evansiroky/node-geo-tz#120]
Hello,
I installed this library to determine the time with respect to time zone. It's working perfectly in local environment.
When I tried to deploy it on aws lambda layer. It's unpacked size increases to 245MB in linux operating system. 
Do you have any idea how to fix it? Because this unpacked size is too much large. On AWS our layer must be smaller than 250mb. 

Thank You so much

**Comment by mishan** [comment]
I've made a patch to switch to a flat file format. It not only gets rid of the >33k directories, but package size goes down by 90%

See PR #127

**Comment by evansiroky** [comment]
#127 has been merged and released as v6.0.2 which should help lessen this problem if not completely resolve the issue. I am closing this issue as a result, but please re-open if this is still a problem.
