### ISSUE TITLE
Installation takes a lot of time

### ISSUE THREAD

**Issue by alerighi** [evansiroky/node-geo-tz#125]
In the package there is a large number of files and directory that makes the installation, and in particular the extraction of the package, very long (in some cases even half an hour), especially with Windows, where the file system is considerably slower than Linux when extracting a lot of files.

**Comment by mishan** [comment]
I've made a patch to switch to a flat file format. It not only gets rid of the >33k directories, but package size goes down by 90%

See PR #127

**Comment by evansiroky** [comment]
#127 has been merged and released as v6.0.2 which should help lessen this problem if not completely resolve the issue. I am closing this issue as a result, but please re-open if this is still a problem.
