### ISSUE TITLE
Module not found: Error: Can't resolve 'fs' in '/Users/bon.huang/Documents/verkada/Verkada-Web/node_modules/geo-tz/dist'

### ISSUE THREAD

**Issue by yellowbonV** [evansiroky/node-geo-tz#135]
I am using webpack version >5, and I am seeing this issue. 
```
Module not found: Error: Can't resolve 'fs' in '/Users/bon.huang/Documents/verkada/Verkada-Web/node_modules/geo-tz/dist'
```

**Comment by evansiroky** [comment]
From the Readme:

> This library is not intended to be used in the browser due to the large amount of files that are included to perform exact geographic lookups.

This is also probably related to #111, so I am closing.
