### ISSUE TITLE
City of Nicosia, Cyprus found in Asia/Famagusta, not Asia/Nicosia

### ISSUE THREAD

**Issue by kshetline** [evansiroky/node-geo-tz#139]
I was using node-geo-tz to verify and update GeoNames timezone data, and stumbled on the odd result of Nicosia, Cyprus identified as being in Asia/Famagusta, not Asia/Nicosia.

```
const { find } = require('geo-tz');

console.log(find(35.1753, 33.3642));
```

Yields: `["Asia/Famagusta"]`

Perhaps different coordinates for Nicosia would have worked better (it is close to the boundary between timezones), but these coordinates do appear like they should be safely inside the borders of the city.

<img width="913" alt="image" src="https://user-images.githubusercontent.com/24473229/179324024-0563ebe6-0227-43e6-981d-77673984bccb.png">

**Comment by kshetline** [comment]
Is this perhaps deliberate? The single city is split in its timezone history?

<img width="952" alt="image" src="https://user-images.githubusercontent.com/24473229/179324716-15a92442-02a0-41d7-a369-e9d2bcd95444.png">

**Comment by kshetline** [comment]
Okay, I guess this is more complicated than I would have expected. From Wikipedia:

> From 30 October 2016 and onwards, Nicosia became the only capital city in the world that had two [time zones](https://en.wikipedia.org/wiki/Time_zones), after the parliament of the de facto Turkish Republic of Northern Cyprus abolished standard time and decided that Northern Cyprus remains at [UTC+03:00](https://en.wikipedia.org/wiki/UTC%2B03:00) year-round, following Turkey's example.[[54]](https://en.wikipedia.org/wiki/Nicosia#cite_note-54)[[55]](https://en.wikipedia.org/wiki/Nicosia#cite_note-55) The following year, due to criticism from the Turkish Cypriot public in the north, the Turkish Cypriot government decided to go back to standard time, following the rest of Europe.

I guess the problem is deciding which side of the "green line" dividing Nicosia you're hoping to find when you look up latitude and longitude for Nicosia.

It's also very confusing to have one of the IANA timezones named after a city which itself has been split between timezones.

**Comment by kshetline** [comment]
Considering what I've discovered looking into this further, I'm going to close this issue.

**Comment by kshetline** [comment]
Once more, with feeling.

**Comment by evansiroky** [comment]
I do believe it is an open question of what side of the line to use or even if there should be an overlap of areas. In my original work, I gave all of the [UN Buffer zone to `Asia/Nicosia`](https://github.com/evansiroky/timezone-boundary-builder/blob/75503290f9fe0ac4c46edf49d647b404c9a314fb/timezones.json#L2540-L2559), but this was before when timezone-boundary-builder had overlapping zones.

As this is an artifact of the data from timezone-boundary-builder, any further discussion should happen in an issue in that repo.
