### ISSUE TITLE
Ocean GMT offset

### ISSUE THREAD

**Issue by pedrolopes10** [evansiroky/node-geo-tz#142]
Why are the GMT offsets in src/oceanUtils.ts going from GMT+12 to GMT-12 instead of the other way around?

Thank you

**Comment by evansiroky** [comment]
This is expected behavior.  You can read more about this in [this entry in the timezone database](https://github.com/eggert/tz/blob/1a0e30a84b2f76663123a4555c2785b450ce06f1/etcetera#L40-L46).
