### ISSUE TITLE
Time zones differ from Google's for same coordinates

### ISSUE THREAD

**Issue by michael-ts** [evansiroky/node-geo-tz#143]
I'm geotagging photographs and using this library to determine what time zone these photographs are in (and adjust the date the photo was taken) so that when they are uploaded to Google Photos the correct time is maintained.  This is because Google Photos treats photos with geolocations as having been taken with a clock in that time zone and thus an incorrect timezone causes the photograph to appear out of order.

I have run into some coordinates which node-geo-tz reports as  'Etc/GMT+3' (which is UTC offset -180 minutes) but which Google translates as "America/Godthab" (which is UTC offset -120 minutes).  This can be confirmed via Google's API at this address (substituting in the latitude, longitude, and one's Google API key):

https://maps.googleapis.com/maps/api/timezone/json?location=${lat}%2C${lon}&timestamp=1665659496&key=${API_KEY}

Here are some samples of latitude/longitude pairs which exhibit this issue:
59.139391, -44.929223
59.142512, -44.913509
59.251590, -44.355566
59.2689529,-44.2648703
59.2795594,-44.2094072
59.287165,-44.170021
59.3158163,-44.019224
59.3180883,-44.0073058
59.3248543,-43.9714859
59.3651078,-43.7566058
59.3680885,-43.7405161
59.3845204,-43.6528836
59.4000356,-43.569093
59.4141028,-43.4928311
59.4206866,-43.4569129
59.4317518,-43.3968338
59.4369211,-43.3687356
59.4406089,-43.3486365
59.4471765,-43.3127218
59.4567126,-43.2604549

I may have additional coordinates to add later as I have additional unprocessed photographs.

**Comment by evansiroky** [comment]
The underlying data being used by node-geo-tz comes from [timezone-boundary-builder](https://github.com/evansiroky/timezone-boundary-builder/) which extracts data from OpenStreetMap. timezone-boundary-builder builds boundaries of timezones according to territorial waters. In the case of all of these coordinates, they fall outside of the territorial waters of Greenland. Therefore, they will result in the `Etc/GMT+3` result.
<img width="458" alt="Screen Shot 2022-10-25 at 9 20 01 PM" src="https://user-images.githubusercontent.com/3112493/197933917-bb089786-5c80-4d15-9705-e541d017e439.png">

I believe things are working correctly with this library, so I am closing this issue.
