### ISSUE TITLE
Why find return an array of timezone ids ?

### ISSUE THREAD

**Issue by Neofield-Dylan** [evansiroky/node-geo-tz#160]
Does find returns an array of timezone ids because of historical timezone changes ? if so, is there any logic of the order timezone ids are returned ? Like the current timezone is the last item ?

**Comment by evansiroky** [comment]
As noted in the [README](https://github.com/evansiroky/node-geo-tz/blob/master/README.md#api-docs):

> As of Version 5, the API now returns a list of possible timezones. There are certain coordinates where the timekeeping method will depend on the person you ask. Also, another case where 2 or more timezones could be returned is when a request is made with a coordinate that happens to be exactly on the border between two or more timezones.
