### ISSUE TITLE
Publish variations of timezone data

### ISSUE THREAD

**Issue by evansiroky** [evansiroky/node-geo-tz#162]
With the additional data products that will be imminently published according to https://github.com/evansiroky/timezone-boundary-builder/issues/113, this project will seek to make the lookup of GPS coordinates using each of these products available in some manner.

Before that, feedback is being sought on how to publish these variations. There has been a variety of build ecosystems that have employed this data, so it is unclear what would work best for making new releases. On the one hand, it could be as simple as bundling all the data together and letting a user choose which entry point to work with, but that could increase the download bundle size substantially.

One option under consideration is to make multiple separate `geo-tz-*` npm packages that would each come packaged with only the data needed to lookup based on whether it's using all zones, just those from 1970 or just those from now. In https://github.com/evansiroky/node-geo-tz/pull/140, a proposal is laid out to add an environment variable as a means to utilize a different data source. Perhaps there are other options too.

Please respond with in this issue with any preference for how the data could be delivered such that it is possible to do lookups with different kinds of underlying data.

**Comment by meezaan** [comment]
First of all @evansiroky thanks for maintaining this package - it's been a great help!

I would prefer the first option of letting the user choose the entry point when invoking a method, with perhaps all zones being the default. 

But I think this primarily depends on which type of users the package is targeted at. Many of us don't understand the intricacies of how the boundaries are identified and why different data sets exist. If it all gets split up, we'll likely be forced to learn, but it may also result in the perception of the package being complicated.

Simple is better - the fact that the package has to be used server side makes the 'size' less relevant in my humble opinion.

I hope this helps make a more informed decision, and once again, thank you very much!
