### ISSUE TITLE
Publish version with ocean data variants

### ISSUE THREAD

**Issue by mortenolsenzn** [evansiroky/node-geo-tz#164]
Hey, thank you for an awesome project!

Would it be possible to publish a version containing ocean data? I can see that #163 opens up the possibility to choose between the data set versions, so would be great if there also was the option to choose if it should include ocean data.

If you agree that this would be useful I can create the PR based on your work in #163

**Comment by evansiroky** [comment]
@mortenolsenzn, Ocean data is already included in all node-geo-tz releases! Whenever the algorithm detects that there are no boundaries found at a GPS coordinate it will fallback to looking up an ocean zone. In doing so, it is possible to avoid adding duplicating coastline boundaries to cut down on the size of the release. See example here: https://github.com/evansiroky/node-geo-tz/blob/0608027787cf39b69214bfe0e4ba9e2ff6ff4edb/src/find.ts#L230-L234

I'll add some more documentation about this in the Readme.

**Comment by evansiroky** [comment]
Docs added in e089c70fffbefb6d0e1dad466df9f0b3a420ea8e.
