### ISSUE TITLE
Unknown time zones, maybe the library could make a better effort?

### ISSUE THREAD

**Issue by magwo** [evansiroky/node-geo-tz#45]
Hello and thanks for a great and interesting library.

I'm wondering about the situations where you get null return values when a timezone can not be found.

When does this happen more specifically, and could the library make an effort to find a roughly accurate timezone anyway?

It seems to me this happens for regions out on large oceans, correct?
But according to many "timezone maps", ocean regions do have time zones. What gives?

**Comment by evansiroky** [comment]
This library's geographic data for the timezone boundaries comes from [Timezone Boundary Builder](https://github.com/evansiroky/timezone-boundary-builder) which only includes definitions of the extent of known areas where timezones are administered by a political entity.

If there are specific coordinates that are clearly inside the territorial boundary of a sovereign nation yet this library is still returning null, I would consider these a bug and will investigate accordingly.

However, out at sea outside of territorial waters (territorial waters are included by Timezone Boundary Builder) there is technically no political entity administering a timezone.  According to the Wikipedia article on [Nautical Time](https://en.wikipedia.org/wiki/Nautical_time), it is up to the individual to decide what time they want to keep when they are not inside the territory of a political entity that administers a timezone.

Therefore it seems that there could be multiple possible ways to determine what time it is in such situations.  I'm curious what your use case is where you would need to determine the timezone at sea.  Do you experience this issue regularly?

**Comment by magwo** [comment]
Thank you for you response.

We don't expect to generally have problems with this as our coordinates will be mostly on land. However I'm worried about glitchy GPS receivers reporting weird and incorrect positions in certain situations, so our code still needs to have an if-statement to handle the null return value.

I think the library would be nicer to use if the "unknown location" behaviour was to return something that corresponded roughly to the vertical bars as seen here: https://www.timeanddate.com/time/map/

In our use case we would vastly prefer a "best guess" based on longitude over a null return value.
Perhaps this behaviour could be optional?

Or how about the possibility to provide a handler function, to the `tz` and `tzMoment` functions? And the library could have a built in such handler to guess from longitude? For example:

```
var name        = geoTz.tz(47.650499, -122.350070, { unknownHandler: geoTz.longitudeGuesser }) // or a custom function provided by user

```

**Comment by magwo** [comment]
I can definitely make a PR if you think the `unknownHandler` pattern is a decent idea.

**Comment by evansiroky** [comment]
I hadn't thought of glitchy GPS inputs.  I like the idea of having an optional argument where you could specify a custom or built-in guesser that could be activated on demand for backward compatibility.  Feel free to send a PR.  👍
