### ISSUE TITLE
Problems with babel builds

### ISSUE THREAD

**Issue by nfroidure** [evansiroky/node-geo-tz#74]
I would like to use this module on a project built with babel but I encountered an issue.

The inside function required here:
https://github.com/evansiroky/node-geo-tz/blob/master/lib/find.js#L4

Is exported as an ES6 module in the `turf` package.
https://github.com/Turfjs/turf/blob/master/packages/turf/index.js#L127

So I get a `inside` is not a function error. I could do a PR to fix this with a line like that one:
```
if ((inside.default || inside)(pt, geoJson.features[i])) {
```

But I think there should be a better way. Any advice on this issue?

**Comment by evansiroky** [comment]
Hmmm, looks like `@turf/inside` [has changed](https://github.com/Turfjs/turf/blob/master/CHANGELOG.md#%EF%B8%8F-breaking-change) to `@turf/boolean-point-in-polygon`.  I wonder if updating to the new package would help.

**Comment by nfroidure** [comment]
Thank you for fixing this. Do you plan to create a version soon?

**Comment by evansiroky** [comment]
Yes, version 4 has been released as of yesterday.  Let me know if that fixed the issue for you.  Btw, this package is not intended to be used in the browser in case you're trying to do that.

**Comment by nfroidure** [comment]
It works perfectly fine ;). Thank you for your efforts!
