### ISSUE TITLE
Subset of timezones/coordinates

### ISSUE THREAD

**Issue by joshuaadickerson** [evansiroky/node-geo-tz#75]
I want to be able to get the timezones for the inputted coordinates, but I know those coordinates will never be outside of certain bounds. Specifically, they are all in the United States, Mexico, and Canada. If they are outside of that, I can default to UTC or something.

I'd like to be able to not have to use 900 MB of memory to fulfill those requests. Would it be possible to get a subset of the coordinates data?

**Comment by joshuaadickerson** [comment]
Sorry, reading in to how this works more, I can use https://github.com/evansiroky/timezone-boundary-builder with `--filtered-zones`. 

I'm going to close this. Maybe some documentation?

Thanks for the great tool!

**Comment by evansiroky** [comment]
While I do maintain timezone-boundary-builder, the feature you're describing could work for this package as well.  It could be possible to add a feature to this library to pass in some config with only the particular zones you'd be interested in.  Another way to do it would be to store zones in memory as you lookup coordinates.  I'm actually going to reopen this issue cause that'd make a good feature.  I may not get around to implementing it for a while, but I'm open to receiving a PR.
