### ISSUE TITLE
quadtree initialized different in index and search step

### ISSUE THREAD

**Issue by mtmail** [evansiroky/node-geo-tz#79]
A location south of Oslo fails to return a timezone in a small area of 10 meters. It's not close to the edge of a timezone and no overlaps, but right on the edge of a cell.

```
lat=59.76555, lon=10 => "Europe/Oslo"
lat=59.76556, lon=10 => "Etc/GMT-1"
[...]
lat=59.76562, lon=10' => "Etc/GMT-1"
lat=59.76563, lon=10' => "Europe/Oslo"
```

`geoTz(59.76556, 10)` finds cell `abcbcadd` (file `data/a/b/c/b/c/a/d/d/geo.buf`) with the boundaries
```
{ top: 59.765625,
  bottom: 59.0625,
  left: 9.84375,
  right: 11.25,
  midLat: 59.765625,
  midLon: 9.84375 }
```

The `Europe/Oslo` polygon in that file
```
 [ [ [ 11.249994, 59.093919 ],
     [ 11.246127, 59.092903 ],
     [ 11.224859, 59.087612 ],
     [ 11.209764, 59.085848 ],
     [ 11.153506, 59.079257 ],
     [ 11.143974, 59.062434 ],
     [ 9.843745, 59.062434 ],
     [ 9.843745, 59.765559 ], 
     [ 11.249994, 59.765559 ],
     [ 11.249994, 59.093919 ] ] ] },
```
has been cut to slightly different boundaries during indexing
```
   min lat 9.843745
   max lat 11.249994
   min lon 59.062434
   max lon 59.765559
```

During indexing the quadtree get initialized with -179.9999/-89.9999 ... 179.9999/89.9999 while the search in `find.js` get initialized with -180/90 ... 180/90.

**Comment by evansiroky** [comment]
Excellent bug report!
